language: node_js
git:
  depth: 10
env:
  global:
  - secure: ZN0bbWBqu8XJwlNTotYu2nMXg0X2O5zRVDjZJLKvQMXCoV/0vVBHq7OD009KJmtLMKa1DMSAph/aCHi/weMZ0LjeN2UMtlJsqLZj3i8TsPBNKQcZwySpoLO5HX8+/GiXpLDHYPQRYPX9fKkMoyOW/DdPwGE9w/m8ZQoWomGS2VoVYYipbWrD6kqKHhsnEFtbX6zQ/OH632fc+8X/QIZrgp8iJ/PNFkLkjcC+ycDqcMrdhOUgbpCW2EuhgeMEV43uCAwubvG9aRxFQoAJMOKLmgPVZdBiSLwQSTbwdzr34U5NNYbXbqapxJyzkS2xX1LY+hy3Yjv9Jsb0DOyALN/tZqQB35qNGAPnSZkuX2Hmgx4Pum12/IufD+XPzWbWJ8aF4ep7vTa/MTUZasz0RlJGFazRcaTsLYE2Nb6TWULZsgweL4ZlAIBdZdgpaKzvc4Kyi6dBJ1oFDf6D52lE+1eAOocr4ri1Eep6DgQ4lYhYNGhFk6lPvciUo0yEKQoBBRBhXWurCzACD5MXaPGRuD5lTUi70xn8PhVc+34TwqOY5R82PhEBL0g58iFiipIFj6tir1dL+9rf9yjMkDY2fkemWNFXuK2ZsiyjK9E/U+wQYU0MwEdcTOGxHc/8M8m7NsMx92Cu1gBVLJ/LqI7bbfKgHMkC/eMCl6+OgMbPXGJVjdI=
  - secure: kMDeq7lWX4ofJ4J5MSLIgBhltLXUVqJyJ4oLv2RuHemujz27sMhnq2Do6LzCcFN4ol8Vy2CNvQAAzvqZXr3G6vQVrsiVCFnmpfYgS5bDVeR81HlbY3BPwLqUEXXZptoPedOP28yWhbPodflF8VfD9nW9U6Y3JB8e5/9je/V2RcYgPeA74CaR8YQvnQIjLBDnIRUvpVhthYxsmvqTSlHt1/R82MVJw3WHZb+D3b/X6au0Hbfnfqblkteusrod+sZpUaKe3kLVyaFIdnEefrXSX/id+BzeFRCwBNeXyAzmD/zLdeQ7LID5aLfCUU4jk6lCJleHe4PwBeUn90ySS32uHjGbvzOhEfFNgjq6wKsnfvxgCEvdY1Eu83P6x9+UNDrijYk7P9UX0KOsglm22WkgPW3AP0b4wVeaxPCBeRonIM6cSlr+QCUMycvt8mR/aFRiyRVg+kH5TFJOHdV2YtDok2swn6yXzcd7LjwtqBJJzbgONoewr0AmnG9G7hsHd2EQf3rMeGQK/nqD6v3p/bTL17gc1NMP3iCEoTk5vIhD+myFTi88P9IsjrxTzFg033VjK1ESHLjKFDS2t0C4aYTGsYsFVS6orQqtR+uUpjqHWjoD1yRVUBaftFaNY99CZtHUuO2baYfhODiB7sF2X10xlGdUT/m36r2aZQ9nJ64YKhk=
matrix:
  include:
  - os: osx
    osx_image: xcode11.2
    env: NODE_VERSION="12"
  - os: linux
    dist: bionic
    env: NODE_VERSION="12"
before_install:
- source ./scripts/install_node.sh ${NODE_VERSION}
- node --version
- npm --version
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- PUBLISH_BINARY=false
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true;
  fi;
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true;
  fi;
install:
- npm install
- if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x ./scripts/add-osx-cert.sh; fi
- if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/add-osx-cert.sh; fi
- travis_wait 30 source ./scripts/package_and_publish.sh
