language: node_js

git:
  depth: 10

matrix:
  include:

  # Mac
  - os: osx
    osx_image: xcode11.2
    env: NODE_VERSION="12"

  # Linux
  - os: linux
    dist: bionic
    env: NODE_VERSION="12"

before_install:
- source ./scripts/install_node.sh ${NODE_VERSION}
- node --version
- npm --version
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- PUBLISH_BINARY=false
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;

install:
- npm install
- npm run build
- source ./scripts/package_and_publish.sh

deploy:
  provider: s3
  access_key_id:
    secure: aqT1Z33bEA9vFsV98L3YzqPK4snepWZEN6TfLBswDwTGVYWxueFga5M/0Qt4qG8MnJeyKb/tzZHe6e+KhmeGdsDPKGvQ9bJdNBVLy2gPvpZtfKO0j35rVgrh60xJ3jwEyivYC32eGIbDx9qn//+t5kh+r6Hqkg1a+EH+G0lJz6s/7CLCYGGdilE8GbIoJeAnEFDDqA8HIpXn9nuJQE6dHbyTou0U0yi2jtelOmrUpE/2HzUZCgnBBqCkPGidSEovwiz5PaeVv2Aus0JgepFpYk4dUnADltKPXXjm3cCDMcnUqFUK6uVgVKIEF4JLKiMxoxfL5xuBLIibJGuWi976XASp3dvgi/KetqIZFUQ5gnbpwDtioFnU5ae+aY8GPjFNnxRIW3dPVuWbpX1JfD8mkaJNDnflE8WrNPzO4lybsf3fETo1TFBNqGB2sOuytckLvh2tcS+SYOiRpX/ZG0FmU3U3+NpajL4+dJQQJPKeANQVzl+a2ro0U2Jmzty4gEsD/aCLrmqcv6dObAqS6U3nkPI1HoO8k7McrywGzdo+3LPCsNQ7iPv3SEwSa5qNA7dvljYjBzy0Y3ulwYgAdHjvbNbg9BwMq/RSlrR6KsdxayeQwOhshdYe4T/EqdemeRgqiH4d1Cb53hNCHdF5xsX6qWCrXJ3/4uTY0RasjczCnYw=
  secret_access_key:
    secure: CGqjn/z/mXDA60fTmz5I9/HXvLSAwPXNfXBwvUAbswO3iZHDXdgWSiOqipj2PC15q6oHBCYp+y7dwH7DJ+yZdfoBSAsITD0RfkYgz2UNkk7rwM5m4klifW4jQr9nt7l21+Nzh2+jXrmiR8nQ6KicIBuYsd4RWXtKYdTzFAbBbcLwMuZ00VR57m5dwRV/3tS8wGBAxig1jvKXFBzZWDKR2lck+ko70/ztQX+POaN0b4YqyCiSN28NoMYfksm+318580n6W5tjduhkGvNPrdkElR78XFdwTl/DzT8SRqtJ2C9RvpaC6a3VaX2/9dUqjnj9cljlKyyW27/RP5hYFK+Rfoe+U1Boq/nE/g4sBfqaK8Hts1pgR8o6WJv4Jh5p+DX8j9aOK4iZkEvn2NFIR/04rJxKWMKMwuaYpGMW279rpDqG64Yj8XbLEa21L4z0g/a7clMkOLxZW/wpQPX4O4FwkXxQj6YqJQWVT90JfWlQq3zEENEPtbhd4aKwf6deG3ht4QSL1ATYYRbxSt1kF8ZANl+/3uidFfP6eiYeaxuO2dB1kYZL5T9tycSrNZKDID2Mdf1IaPa31JAZFV1MeFghOFjqbDo3f065v13fqzdWhMdboau7OcaDY+Ud764kcBipDRmqL3PKADHVifnToOuwFOWDULwwEO3941FcZ1/N2N8=
  bucket: ziti-mattermozt-binaries
  skip_cleanup: true
  region: us-east-1
  local_dir: release
  upload-dir: travis-ci-builds
  acl: public_read
  on:
    repo: netfoundry/MattermoZt
