language: node_js

git:
  depth: 10

matrix:
  include:

  # Mac
  - os: osx
    osx_image: xcode11.2
    env: NODE_VERSION="12"

  # Linux
  - os: linux
    dist: bionic
    env: NODE_VERSION="12"

before_install:
- source ./scripts/install_node.sh ${NODE_VERSION}
- node --version
- npm --version
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- PUBLISH_BINARY=false
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;

install:
- npm install
- npm run build
- source ./scripts/package_and_publish.sh

deploy:
  provider: s3
  access_key_id:
    secure: "V2hxMAAr2CENX15RLUjXXxabrVc33BvRcmNIeDXzdJ1USAQtawmn2M1wyvuHFGUimXNTKbZKLVpqpWkdFfB5b7FLiGvEALFgqs+ERzXGl/JNc5YZBerIgEHs8rhbLNWDlZ8wFTnF++A0oqxT54YaCGguyPWSgQTqhkUGcpb5ezzpdB2Jv5fw4ez/qWEq7wXf9l9YAgqh/L0wFETZfVjJOOkV8FX5KP1j1I+O5+ZR+LODbLY6uryCIKwIO7NbHCO8ILpgoPurpbi11i1joMO02luSXyoDt1aGxh6VVR6zp4gUmKJyvXIf8hna+7+h7gbnDIBtMxbyZXbE+GUAtHx9ezLAOnaqlL9YRs/9vmQypO8/WrZ/pWWUkvARDgrXbW+Z3A5Qp4xA6ik3FCirvc8MFSWdBsuR3GyfR3d4Q4emlpArwwXhaZC/DgD+CbuNKMGLrfGGOCKfRIB7jtgE585obnzgYJ11gZDgjUvZgYHXDqPcTg4UjuPx6EXTGa4SYrUPnAeII0VZo+0xEOZIVXpDvjXhx+1X6NTtBNMOXfrtZMz/fXKxlTRPvnxVC6EDtZYWd+Uezrh+x9E4xgQ0kQGvQDnXMQ8pZX8gcYBhmnUdxm+HM0/dS+jieqkrp05WIJUVf9h/KUZBAzSgFkHP+boXFDQ53OLdLV1omRDahf8QHnA="
  secret_access_key:
    secure: "oUf+r2N2jbiwQib3xnrWqybEj+SvHGuQhiXyOvJ2MX0mBlF5ep6V5CMVPWHQ2AELGMkLLCQSD2SEmHyGTzVTZp4NaxQuv9niqoidHtpmNWcfpUwMtO8xskPPY9QEsBYh1u+1dmNHC5SuOuQ6aQAk/+WsGCn6zsC43olWU4nWSVM3twvLoxy9oX8fJTKnYxOAS/kofjyHKS2r453zXpuc5+O6ZMXqpfo58Y9vAqOKu1mytR6I2M4CseKWLNJKeXu391rCAgKKNPCAfcunGWH0ka9xR8PspRuksZjH5ZyHAuBthSrtHdiWEF5TbSGJcbpEn5zAnw4uU4eX1P/S4WYHL9QM4MK0rWcl4Pox1sXOdz3JoAuNu8G+V6FsGvb9HkjJXlYqreGizGd3jpNwNsM/MXaC3AaeW3Juoisr/qEVUChw0NQRYalx1uLtntP377IAeUPgiKUYpev1nR9lw0wASlCkmg+Y4NQdSXacCJIFdhvpYWZSgYoEwo4B1rqEFwLKDsN+qHL+5hkuek2BvAxJmKDEQHu6kbhbiIexGPUpvNX3tx7CHrjwOZhpDAntRnrVmdCxHCSZZQaP7IGsCCMywLSop7lIhEK0y5XwO90coSTRYqRvW2JWUwHOZQ6iIqodpQFuzWrUG9eoKzXHNlnC+zhm4GJuzl7YXaeuvKImdtQ="
  bucket: ziti-mattermozt-binaries
  skip_cleanup: true
  local_dir: release
  upload-dir: travis-ci-builds
  acl: public_read
  on:
    repo: netfoundry/MattermoZt
