language: node_js

git:
  depth: 10

matrix:
  include:

  # Mac
  - os: osx
    osx_image: xcode11.2
    env: NODE_VERSION="12"

  # Linux
  - os: linux
    dist: bionic
    env: NODE_VERSION="12"

before_install:
- source ./scripts/install_node.sh ${NODE_VERSION}
- node --version
- npm --version
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- PUBLISH_BINARY=false
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;

install:
- npm install
- npm run build
- source ./scripts/package_and_publish.sh

deploy:
  provider: s3
  access_key_id:
    secure: RyAuHlUDjUhoO9Lqke8FfvrNE7M/gO86ZIf1MhrjGEU/qF1Ab+nDYubVsKXdSXVNjpi4rXFbLkPIXJd5OMEosjt8TbtfbeYIX14NAyDsDw5ZRuyupK2IJFvcdNtnOJGqLemIYHQW8/zQZvlqGiQyiXFZyORcCeyhvhBO2EJL3fi0c4OjsMkAFNtrqbKWsUKWp5iX6zqoKi02WHvbmrYTeAX3eSW+tQyi6zYuR4LiB+dQkXGRh3WGiMFvrsxfQB+We/CegJzwjhEr+0kNNjtgJL5qObWTHWJKDyLlfSb4t231ZiweaXiioUqA34rsOP/QAgp00ZJKALD0i/u/bBY3septC3Y+bKYSCDAIOvT7CiWu/KY7Y9SQIznz9xVR5bK1EofYLpMALKNZWrqj7Wwopn4O80arD8h+YMcE/vhWcm0YnjYHEX2q5LjPMIb/qG8mv+SeZkHDwTaDNa+hz+pe0/dY7m8vzn0ZXfVPjrxx5vPwWf4g30F9MHA9nK3FYlfVfC7V4OtCVhVxvETzn1uQKqpAsTFrPavV3RIoSR2WUMWBYAJhVtjuI/Q8/0kc5yOtkQOXltHkq7h9N/rJzS1LFo9D8YQ3x9hruTr1T1o4fgP+lODYBg2Dxj//IUNYHxdB8Waq2PuLPknNnXb8UQ2760R6YuaqCUc6F+n7H69TntE=
  secret_access_key:
    secure: Y6Q66w74q6hBsfevCOkqlYJMjVQEG7zVyQBknSsFtdSn3Bcx3UldRPxU5w6E/VFNCxCKu9ht1tRQEH7QsSOnbfCjthDcLptXjyn9SliPo+Q9RO6UFFCMlH7yw1IrtdjkACYb8w1OYJlxztUfKc7KCo7U278xciJ5LvNz9m8ZSTePtpqP1+Oj8rtXqPOtCbkoraMgMuDGESZ6qB4wq++jVabMI62vYRWoHYDxjMQ+K6twGYpvWsA4CJkPJB8LsQ/7bDpBvUHZ9gPkNCDpOWFwfiepOU7OXMD6c4agHiMkhFIVREomAK9ySHRJ+13IcjrmVGQSjXPBnwx3AaZORfle0X0rO2PetV6FSE/W9GCI2MRzMEjTyPsoF7QNb8IjjqGSeYYIAFoe2Fjl35oA2SdygXz+bSeVUXMGa5JxwTUh5GATvghfKbS4EzfDPOiyY/yUt0QQ6swIV7/85xfC38E7YNcyKDg1Y27cRgWJ1SJnto6VzmREk3DQM3zHOUIdLPSeiXZKIsBOsEigTmOpyeqFDOS2ZM3oqOg+QdUi/vctrGWFZupk2HGnlc+jQsof7Z6kThdLEa4NlWONVC6zOnCW7ZVENlPoX94kHjlk2+otZL8YnsYfhh7SPeVgtkktIp7uOwlKaOKkOlXhmAP4w9gtgMFIIvEqxS3WZRvgrANhqgY=
  bucket: ziti-mattermozt-binaries
  skip_cleanup: true
  local_dir: release
  upload-dir: travis-ci-builds
  acl: public_read
  on:
    repo: netfoundry/MattermoZt
