language: node_js
git:
  depth: 10
env:
  global:
  - secure: ZN0bbWBqu8XJwlNTotYu2nMXg0X2O5zRVDjZJLKvQMXCoV/0vVBHq7OD009KJmtLMKa1DMSAph/aCHi/weMZ0LjeN2UMtlJsqLZj3i8TsPBNKQcZwySpoLO5HX8+/GiXpLDHYPQRYPX9fKkMoyOW/DdPwGE9w/m8ZQoWomGS2VoVYYipbWrD6kqKHhsnEFtbX6zQ/OH632fc+8X/QIZrgp8iJ/PNFkLkjcC+ycDqcMrdhOUgbpCW2EuhgeMEV43uCAwubvG9aRxFQoAJMOKLmgPVZdBiSLwQSTbwdzr34U5NNYbXbqapxJyzkS2xX1LY+hy3Yjv9Jsb0DOyALN/tZqQB35qNGAPnSZkuX2Hmgx4Pum12/IufD+XPzWbWJ8aF4ep7vTa/MTUZasz0RlJGFazRcaTsLYE2Nb6TWULZsgweL4ZlAIBdZdgpaKzvc4Kyi6dBJ1oFDf6D52lE+1eAOocr4ri1Eep6DgQ4lYhYNGhFk6lPvciUo0yEKQoBBRBhXWurCzACD5MXaPGRuD5lTUi70xn8PhVc+34TwqOY5R82PhEBL0g58iFiipIFj6tir1dL+9rf9yjMkDY2fkemWNFXuK2ZsiyjK9E/U+wQYU0MwEdcTOGxHc/8M8m7NsMx92Cu1gBVLJ/LqI7bbfKgHMkC/eMCl6+OgMbPXGJVjdI=
  - secure: kMDeq7lWX4ofJ4J5MSLIgBhltLXUVqJyJ4oLv2RuHemujz27sMhnq2Do6LzCcFN4ol8Vy2CNvQAAzvqZXr3G6vQVrsiVCFnmpfYgS5bDVeR81HlbY3BPwLqUEXXZptoPedOP28yWhbPodflF8VfD9nW9U6Y3JB8e5/9je/V2RcYgPeA74CaR8YQvnQIjLBDnIRUvpVhthYxsmvqTSlHt1/R82MVJw3WHZb+D3b/X6au0Hbfnfqblkteusrod+sZpUaKe3kLVyaFIdnEefrXSX/id+BzeFRCwBNeXyAzmD/zLdeQ7LID5aLfCUU4jk6lCJleHe4PwBeUn90ySS32uHjGbvzOhEfFNgjq6wKsnfvxgCEvdY1Eu83P6x9+UNDrijYk7P9UX0KOsglm22WkgPW3AP0b4wVeaxPCBeRonIM6cSlr+QCUMycvt8mR/aFRiyRVg+kH5TFJOHdV2YtDok2swn6yXzcd7LjwtqBJJzbgONoewr0AmnG9G7hsHd2EQf3rMeGQK/nqD6v3p/bTL17gc1NMP3iCEoTk5vIhD+myFTi88P9IsjrxTzFg033VjK1ESHLjKFDS2t0C4aYTGsYsFVS6orQqtR+uUpjqHWjoD1yRVUBaftFaNY99CZtHUuO2baYfhODiB7sF2X10xlGdUT/m36r2aZQ9nJ64YKhk=
  - secure: lqKrbDHEt/C6VB3mzLgIUPfc9jFfL3sCD9haHa+6/IL2AeHGs4y32KiAVbCd+p020HSMJSXZeqazB+qMxj6EWdzcLtGpW0GnrfguZYMVdKJ8J8nTm6zdtm7xHfIsUhEFbVX4bYPdD0H1jxFUPpxQ7kQ48e3FixqyaaYhrKpRfPd1dW6Vvs2Sj0Zgc9I/vnX+HykNSQZ3cBLeHDdMO/9kgP7wd7ebWwQLZMd9VGRgEK/aDGxMs6EiIKsSjbmxofwQAEePaMnIetUCrgkbTmQFrlP2Y0VXiJzI1fH351N56VJVskV+htFuhRanrbqDig7H96wogcU8axijGXJqFsG6CK3sWHCkVy+zmTttlR5fq06CbQmdIjPBpksiXPrN70ewHbDG2tOgsD6MiHEInllJQ8hGWmpZKeQvdvKCqvMUsbEhXx3t1mnqIq/IvqHxsaonxjJJciD97KgvinnNeKjwfv2oW0MnOD2xUZKbNoKG8EUqFVkUTfZddEvvwGVPe8vIatryEDG7hKt1+gJL5VTJZ6i/kIJfCq0pHZAmjW7wZMwMEHWRPe3+poX/NEkPUNOoxy5ktv9m90XpAp723Q+uIDHMZx9vRcgcYUudLfVw9T3T6xQbDXFZeJ3mPOYcxebi/wrn2HkrVDiWNxpYMxrSMfRvaWEYkIymwrCgcCNIZZ0=
  - secure: ilkZrGBtZIgJ6ho/YKiuVWyRux2JTZOWShMKsSCmvbVwDpUb9hnKXlXLX4FaUuauYkLvInGdV1H/ljBhn3weWtk9fyNX2isn4+Hu+ZwcFDA2b9BnnWF4HfJiTdKD8whTriUfQd7XdRHhnJvpcSHFEG645RsoHOW604xcvYfNMrJjk1Ked+rfjz3k69PcbXg4nIUB5RJMgCf4dL+e45TwW2FrtCI8ipZoMYPjKC2xnon1CluDgLVP+eGUtydF4T52GRMDsMJsGuDE9c+Xx2B0a97WI7TOg0T0p6KS8+fSIw89KEGg2N+EebXO8IC/2rUmqU8afsd7RSzH+GfU/S1AnxWAYaHZDUIV6px3GHQv18/PBBxfl3YW0WRB2W4YwWOJdgRyPMlCLT917ZWrI953l7G4WvVoGf6UJ4cdqFvCr3e9XhbRKPz3WPR2tf+K0A1hCWGVlKaSjMtmlCSbpNUU68TWZ6V2XfaKidi5CL8b3qcMPDLOQ1cQFB9AjgDXj/Io36NU9obMtF0mXEieseY+tD3SUSZfjQgqR84eU4DCxow9s5MQsIizCQ8+0vtfFlOti5nkcmco0aZOEjh8XhDc2j44eclRtC11xoWvKxl/q3enHLzcuhqESTgH/pwyNRCklZYHZxVaMHXw9M+7UBd95BW0lKnxS12yINz7EyJgukc=
matrix:
  include:
  - os: osx
    osx_image: xcode11.2
    env: NODE_VERSION="12"
  - os: linux
    dist: bionic
    env: NODE_VERSION="12"
before_install:
- source ./scripts/install_node.sh ${NODE_VERSION}
- node --version
- npm --version
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- PUBLISH_BINARY=false
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true;
  fi;
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true;
  fi;
install:
- npm install
- if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x ./scripts/add-osx-cert.sh; fi
- if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/add-osx-cert.sh; fi
- source ./scripts/package_and_publish.sh
