
platform:
  - x64

configuration:
  - Release

environment:
  AWS_ACCESS_KEY_ID:
    secure: GIQzwkV21ZqWhzZ0ii13r4dOEZ6Pkq8r6Jajx18uEaY=
  AWS_SECRET_ACCESS_KEY:
    secure: 7sxn6236C/oltJYJfel3ISUxQfuBfB44QqdWs0Thjy+U3s+6MPugW8CGVlC8p0o8

  matrix:
    # - nodejs_version: 11
      # platform: x64
    - nodejs_version: 12
      platform: x64
    # - nodejs_version: 13
      # platform: x64
    # # electron
    # - nodejs_version: 12
    #   platform: x64
    #   NODE_RUNTIME: electron
    #   NODE_RUNTIME_VERSION: 7.1.0
    #   TOOLSET_ARGS: --dist-url=https://atom.io/download/electron

os: Visual Studio 2015

build:
  - scripts\build-appveyor.bat

after_build:
  - ps: Get-ChildItem .\release\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  provider: S3
  bucket: ziti-mattermozt-binaries
  region: us-east-1
  set_public: true
  folder: $(APPVEYOR_PROJECT_SLUG)/$(APPVEYOR_BUILD_VERSION)
  # folder: travis-ci-builds
  # artifact: release\mattermoZt-desktop-4.3.0-zitified-001-win-x64.zip


test: OFF
